### ISSUE TITLE
Pickle.dumps returns different values for each run and will cause error when getting lmdb values

### ISSUE THREAD

**Issue by xiaomengyc** [mshukor/TFood#2]
I have run into a strange issue. After I properly prepared the lmdb file by running` h5py_to_imdb.py `script, I started the training script. It stoped at the line `buf = self.txns[env_name].get(self.encode(index))`. At first, I thought it must be some mistakes with the preperation step, so I went to rerun the preprecessing steps  and checked it for several times. I didn't find any problem with it. Then I compared the returned values from `pickle.dumps() `between the preprecessing script and the training script. I found a strange problem, the values between them are different!
![image](https://user-images.githubusercontent.com/6275787/168723540-4647420d-865f-40fb-9b92-430cce5090d4.png)
![image](https://user-images.githubusercontent.com/6275787/168723720-1f1d058d-8eed-4b2a-9e59-3299434fceb4.png)

I googled it and tried to solve it. I tried added hash declaration as suggested by https://stackoverflow.com/questions/26218853/pickle-dumps-returns-a-different-output-on-each-call

Does anyone have some advices to solve this problem?
Thanks in advance!

**Comment by mshukor** [comment]
Hello, I didn't encounter this issue, `pickle.dumps()`  gives the same value for the same python version:
I use conda, here is with a python 3.9.5:
```
Python 3.9.5 (default, Jun  4 2021, 12:28:51) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pickle
>>> pickle.dumps(0)
b'\x80\x04K\x00.'
>>> pickle.dumps(0)
b'\x80\x04K\x00.'
>>> 
```
And here with python 3.7:
```
Python 3.7.11 (default, Jul 27 2021, 14:32:16) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pickle
>>> pickle.dumps(0)
b'\x80\x03K\x00.'
>>> pickle.dumps(0)
b'\x80\x03K\x00.'
>>> 
```
But yes, it is not consistent across python versions. If the issue comes  from pickle randomization I suggest to do the preprocessing and training in the same conda environment with a python version >= 3.7.11

**Comment by xiaomengyc** [comment]
Hi,
Thanks for your reply!
I am working on a cluster environment and the conda environment, including the python version, packages and so forth, are exactly the same. The only variable is I ran on different nodes (machines). I checked the results of pickle.dumps. For some nodes, it returns  `b'\x80\x03K\x00.'` while some other nodes return `b'\x80\x04K\x00.'`. 

I have also tried to use `str(idx).encode()` as the key to avoid using `pickle.dumps()`. It can get the values for some of the lmdb files but it still reports the same error when reading one of the lmdb file. I  haven't looked into the details. 

I thinks run all the preprocessing and training script on one specific node would be a solution before solving this issue for good.

Please give me some advices if you know the direction of solving this issue. I  will post the solution here if I found it finally.

Best

**Comment by xiaomengyc** [comment]
I finally changed the way of generating keys by avoiding using the `pickle.dumps()`. I use `str(idx).encode()`  as the key and the problem is solved.
