### ISSUE TITLE
Some bugs in source codes of TFood 

### ISSUE THREAD

**Issue by Acura-bit** [mshukor/TFood#7]
A bug named "Bus error (core dumped)" occurs when I launch the training procedures. Just as below:
![image](https://github.com/mshukor/TFood/assets/55222653/dd614e3b-0147-417d-8244-9ce56c61b4f7)
Could you please upload the correct codes of TFood? The sooner, the better. Thanks.

**Comment by mshukor** [comment]
Hello, I didn't encounter this error using this code, it does not seem to be coming from the implementation. However, you might need higher memory (mainly RAM)

**Comment by Acura-bit** [comment]
Thanks for your reply. I have addressded this issue.
